server:
  name: raft-kv
  addr: 127.0.0.1:2317
  cache-cap: 128

raft:
  is-voter: false
  use-loopback: false
  bootstrap: true
  port: 2318

lsm:
  level0-size:  100
  part-size:  4
  threshold:  3000
  check-interval: 5
  compress-interval: 10